spring:
  application:
    name: Tagify
  data:
    elasticsearch:
      clients:
        uris: http://localhost:9200
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    ollama:
      chat:
        enabled: true
        options:
          model: llava
          format: json
          keep-alive: 5m

      base-url: http://localhost:11434

# required : 배포 이후 logback을 통해 환경별 세부 관리가 필요함
logging:
  level:
    root: INFO

app:
  config:
    max-file-size: 10485760 # 10 * 1024 * 1024