name: Auto Merge PR

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && github.event.check_suite.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Auto-merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          PR_URL=$(jq --raw-output .pull_request.url "$GITHUB_EVENT_PATH")

          echo "Fetching PR details for PR #$PR_NUMBER"
          PR_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $PR_URL)
          PR_STATE=$(echo "$PR_DATA" | jq -r .state)
          PR_MERGEABLE=$(echo "$PR_DATA" | jq -r .mergeable)

          if [[ "$PR_STATE" == "open" && "$PR_MERGEABLE" == "true" ]]; then
            echo "Merging PR #$PR_NUMBER"
            curl -s -H "Authorization: token $GITHUB_TOKEN" -X PUT -d '{"merge_method":"merge"}' "$PR_URL/merge"
          else
            echo "PR #$PR_NUMBER는 병합할 수 없는 상태입니다"